### ISSUE TITLE
Environment variable init values

### ISSUE THREAD

**Issue by codetent** [codetent/crypta#11]
At the moment new values need to be added to the secret store by calling `crypta set ...`.
As secrets are usually handled via environment variables in CI/CT environments, it would be necessary to call `crypta set ...` for each defined environment variable in order to pre-populate the secret store for later secret retrieval. (Of course, one could also use the environment variables directly where necessary, but this would require different handling of the secrets for CI/CT and local development usecases. Crypta is developed to exactly bridge this gap, and streamline/unify the credential handling for both usecases.)

Therefore, crypta should automatically pre-populate values from environment variables.

The environment variables have the following format: `CRYPTA_SET_<KEY>`. The value given for `<KEY>` will be used as the name with which the value of the environment variable will be added to the secret store.

The environment variables are parsed once when the daemon starts. They can then be retrieved by calling `crypta get <KEY>`

The pre-populated values in the secret store can be overwritten by calling `crypta set ...`, and therefore only provide initial default values.

**Comment by maruu** [comment]
Shall the environment variable override directly affect the `get` command of the client, or shall it set default values in the daemon?

**Comment by maruu** [comment]
> Shall the environment variable override directly affect the `get` command of the client, or shall it set default values in the daemon?

Nevermind. I think the handling is easier in the daemon, as it will also allow to overwrite the value defined by the environment variables if necessary.

**Comment by codetent** [comment]
Since the environment variables should mainly handle the CI purpose where the environment variables are always set, I would prefer to not start the daemon at all. It is not required since the values are stored in the environment variables anyway and it should always take those. Otherwise, it is hard to understand if you set the secrets directly but other values will be taken (e.g., because another command sets another value). Therefore, I would return the values directly without starting or interacting with the daemon.

**Comment by maruu** [comment]
Wouldnt this limit the possible usecases "by-design"?

Don't you think that local usecases with sane default values in Environment variables, but with the possibility to overwrite them via the tool might be useful? 

If we were to move some of the "main application logic" into the client I fear that this will limit future usecases "by our architectural design choices".

Also, i would personally prefer if the way to use the tool is always the same. It involves the client & the daemon, regardless of the context in which it runs. If we now start to implement "special usecases in certain scenarios" I fear that the tool will get more complex. Especially when I think about the "auto-start daemon feature" that is also planned. I would prefer if we move most of the logic into a central component, and not distribute it between the client and the server. This would also allow us to test most of the logic on component level (focusing on one component), instead of end2end tests. But I have to admit that this is a personal preference, and I am not sure what the state-of-the-art for this is at the moment.

Let me know what you think

**Comment by codetent** [comment]
iImplementation wise it makes probably more sense to move it to the daemon so that the client logic is always the same. I'm not sure if there is a hybrid scenario where you will have environment variables and values provided by the user in parallel but you are right, it probably makes sense to not fully limit this special case. Therefore, I would be with you to implement it on daemon side.
